export const TRAVEL_VOCABULARY = {
  fullTrip: [
    // Planning intent
    'trip plan',
    'full trip',
    'plan a trip',
    'plan my trip',
    'plan the trip',
    'book a trip',
    'itinerary',
    'travel itinerary',
    'travel schedule',
    'schedule my trip',
    'plan everything',
    'routine trip',
    'whole trip',
    'entire trip',
    'complete trip',
    'organize my trip',
    'arrange my trip',
    'help me plan',
    'help plan',
    'trip planner',
    'travel planner',
    'vacation plan',
    'holiday plan',
    'plan my vacation',
    'plan my holiday',
    'trip outline',
    'day by day plan',
    'day-by-day itinerary',
    'multi-day plan',
    'week trip',
    'weekend trip',
    'getaway plan',
  ],

  flight: [
    // Core terms
    'flight',
    'flights',
    'airline',
    'airlines',
    'plane',
    'fly',
    'flying',
    'air travel',
    // Departure / Arrival
    'departure',
    'depart',
    'departing',
    'arrive',
    'arrival',
    'arriving',
    'land',
    'landing',
    // Airport
    'airport',
    'terminal',
    // Ticket types
    'ticket',
    'tickets',
    'air ticket',
    'plane ticket',
    'round trip',
    'round-trip',
    'return flight',
    'return ticket',
    'one way',
    'one-way',
    'one way ticket',
    'direct flight',
    'nonstop',
    'non-stop',
    'connecting flight',
    'layover',
    'stopover',
    'transit',
    // Booking
    'book a flight',
    'cheap flight',
    'flight deal',
    'flight search',
    'find flights',
    'flight options',
    'economy class',
    'business class',
    'first class',
    'carry-on',
    'checked baggage',
    'luggage allowance',
  ],

  hotel: [
    // Accommodation types
    'hotel',
    'hotels',
    'room',
    'rooms',
    'hostel',
    'guesthouse',
    'guest house',
    'motel',
    'resort',
    'villa',
    'apartment',
    'airbnb',
    'rental',
    'accommodation',
    'accommodations',
    'lodging',
    'place to stay',
    'where to stay',
    'somewhere to sleep',
    // Booking actions
    'booking',
    'book a hotel',
    'book a room',
    'reserve a room',
    'hotel reservation',
    'check-in',
    'check in',
    'check-out',
    'checkout',
    'check out',
    'overnight',
    'overnight stay',
    'stay',
    'staying',
    // Preferences
    'budget hotel',
    'cheap hotel',
    'luxury hotel',
    'boutique hotel',
    'hotel near',
    'hotel in',
    'hotel recommendation',
    'best hotel',
    'hotel review',
    'hotel rating',
    'breakfast included',
    'all inclusive',
    'wifi hotel',
    'pet friendly hotel',
    'family hotel',
  ],

  weather: [
    // Core weather
    'weather',
    'weather like',
    "what's the weather",
    'what is the weather',
    'forecast',
    'weather forecast',
    'weather report',
    // Temperature
    'temperature',
    'how hot',
    'how cold',
    'how warm',
    'heat',
    'cold',
    'warm',
    'hot',
    'freezing',
    'chilly',
    'mild',
    // Conditions
    'climate',
    'rain',
    'raining',
    'rainy',
    'sunny',
    'sunshine',
    'snow',
    'snowing',
    'snowy',
    'storm',
    'wind',
    'windy',
    'cloudy',
    'fog',
    'foggy',
    'humidity',
    'humid',
    'dry',
    // Season & timing
    'best time to visit',
    'best season',
    'what to wear',
    'what should i pack',
    'what to pack',
    'packing list',
    'rainy season',
    'dry season',
    'monsoon',
    'summer weather',
    'winter weather',
    'spring weather',
  ],

  places: [
    // Attractions
    'attractions',
    'tourist attractions',
    'top attractions',
    'must see',
    'must-see',
    'must visit',
    'must-visit',
    'landmarks',
    'sightseeing',
    'things to do',
    'what to do',
    'activities',
    'activity',
    'points of interest',
    'places to visit',
    'places to go',
    'what to see',
    // Food & Drink
    'restaurant',
    'restaurants',
    'where to eat',
    'food',
    'local food',
    'street food',
    'best food',
    'eat',
    'dining',
    'dinner',
    'lunch',
    'breakfast spot',
    'brunch',
    'cafe',
    'coffee shop',
    'coffee',
    'bar',
    'bars',
    'pub',
    'cocktails',
    'nightlife',
    'club',
    'clubs',
    'night out',
    // Shopping
    'shopping',
    'shop',
    'market',
    'markets',
    'souvenir',
    'souvenirs',
    'mall',
    'local market',
    'flea market',
    // Discovery
    'hidden gems',
    'off the beaten path',
    'local favorites',
    'local spots',
    'underrated',
    'secret spots',
    'best places',
    'popular places',
    'top places',
    // Specific types
    'museum',
    'museums',
    'beach',
    'beaches',
    'park',
    'parks',
    'temple',
    'temples',
    'nature',
    'hiking',
    'viewpoint',
    'view',
    'photo spot',
    'instagram spot',
  ],

  tips: [
    // General advice
    'tips',
    'tip',
    'advice',
    'suggestions',
    'recommendation',
    'recommendations',
    'things to know',
    'what to know',
    'what should i know',
    'need to know',
    'good to know',
    'heads up',
    'local tips',
    'travel tips',
    'insider tips',
    'insider guide',
    // Culture & etiquette
    'etiquette',
    'culture',
    'customs',
    'local customs',
    'dress code',
    'what to wear',
    'appropriate clothing',
    'respect',
    'do and dont',
    "do's and don'ts",
    // Money
    'currency',
    'money',
    'exchange rate',
    'cash',
    'credit card',
    'atm',
    'tipping',
    'how much to tip',
    'cost',
    'budget',
    'expensive',
    'cheap',
    'affordable',
    'how much does it cost',
    // Safety
    'safety',
    'safe',
    'is it safe',
    'dangerous',
    'scam',
    'scams',
    'pickpocket',
    'crime',
    'emergency',
    'emergency number',
    // Language
    'language',
    'speak english',
    'do they speak',
    'translator',
    'useful phrases',
    'common phrases',
    // Logistics
    'visa',
    'visa required',
    'passport',
    'sim card',
    'local sim',
    'internet',
    'data plan',
    'plug adapter',
    'voltage',
    'time zone',
    'jet lag',
    'transportation card',
    'getting around',
  ],

  route: [
    // Route planning
    'route',
    'routes',
    'directions',
    'how to get',
    'how do i get',
    'getting there',
    'get there',
    'stops',
    'itinerary stops',
    'places to stop',
    // Tours
    'tour',
    'tours',
    'day tour',
    'day trip',
    'half day tour',
    'guided tour',
    'self guided',
    'self-guided',
    'walking tour',
    'bike tour',
    'food tour',
    'night tour',
    'sightseeing tour',
    // Movement
    'move between',
    'travel between',
    'get from',
    'go from',
    'commute',
    'transfer',
    'transit route',
    'public transport',
    'bus route',
    'train route',
    'metro',
    'subway',
    'tuk tuk',
    'grab',
    'taxi',
    'drive',
    'road trip',
    'scenic route',
    'fastest route',
    'best route',
  ],

  destinationExplorer: [
    // Discovery & overview
    'explore',
    'exploring',
    'tell me about',
    'tell me more about',
    'what is it like',
    "what's it like",
    'destination overview',
    'destination guide',
    'city guide',
    'country guide',
    'travel guide',
    'discover',
    'overview of',
    'about the city',
    'about the country',
    'about the place',
    'introduction to',
    'intro to',
    // Visit intent
    'visit',
    'visiting',
    'i want to visit',
    'planning to visit',
    'travel to',
    'travelling to',
    'traveling to',
    'going to',
    'trip to',
    'vacation in',
    'holiday in',
    'thinking about going',
    // General interest
    'is it worth visiting',
    'should i visit',
    'why visit',
    'reasons to visit',
    'what makes it special',
    'highlight',
    'highlights',
    'famous for',
    'known for',
    'popular for',
    // Comparison
    'better than',
    'compared to',
    'vs',
    'versus',
    'or',
    'which is better',
    'which should i visit',
    // Vibe & feel
    'vibe',
    'atmosphere',
    'feel of',
    'vibe of',
    'culture of',
    'lifestyle',
    'locals like',
    'what do locals do',
  ],
} as const;

export type TravelIntent = keyof typeof TRAVEL_VOCABULARY;

export const buildVocabularySection = (): string =>
  Object.entries(TRAVEL_VOCABULARY)
    .map(([intent, keywords]) => `- ${intent}: ${keywords.join(', ')}`)
    .join('\n');
